version: "3.8"
name: alerting

services:
  postgres:
    container_name: postgres
    image: 'postgres:13.1-alpine'
    restart: on-failure
    env_file: environments.env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 5s
      timeout: 30s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql

  localtunnel:
    image: efrecon/localtunnel
    container_name: localtunnel
    restart: on-failure
    env_file: environments.env
    command:
      --local-host host.docker.internal --port ${ALERTING_SERVER_PORT} --subdomain alerting

  bot:
    container_name: bot
    build:
      dockerfile: Dockerfile
    env_file: environments.env
    ports:
      - "${ALERTING_SERVER_PORT}:${ALERTING_SERVER_PORT}"
      - "5005:5005"
    depends_on:
      localtunnel:
        condition: service_started
      postgres:
        condition: service_healthy